<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddCompany2</name>
   <tag></tag>
   <elementGuidId>42c07f99-d7db-4bf6-95e4-785d68063560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddCompany2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddCompany2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddCompany2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setCompanyInfo(this.id);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- None -20 / 20 Genesystems3SBioABT Holding CompanyAchaogenAeolus Pharmaceuticals, Inc.Aimmune TherapeuticsAlentic Microscience, IncAlexion PharmaceuticalsALK-Abello A/SAllergan, PlcAllerteinAmgenAngion, Inc.Araim Pharmaceuticals, Inc.Arca Bioharma, IncArmed Forces Radiobiology Research Institute (AFRRI)Aronora, Inc.ArQuleAstellas Pharma Global Development, IncAtox BioaTyr PharmaAugmentative BioTherapeutics LLCAvaxia Biologics, Inc.Baxter Healthcare CorporationBayerBCN BiosciencesBerlexBioAegis TherapeuticsBiogenBioIncept, LLCBiological Mimetics, Inc.BioMimetixBiosyn CorporationBio-Tech PharmacalBiotheraBioTransplant Inc.Bolder BioTechnology, Inc.Bristol Myers SquibbC Sixty Inc.CalibrCalifornia Institute for Biomedical ResearchCalista Therapeutics, Inc.Canadian Institutes of Health Research (CIHR)CangeneCelldex TherapeuticsCellerant TherapeuticsCellular Dynamics, Inc.Centocor, Inc.Ceramedix Holding, LLCCeramide Therapeutics, LLCChironChrysalis BiotherapeuticsCircassia LimitedCleveland BiolabsColumbia UniversityCorbus Pharmaceuticals, Inc.Coronado BiosciencesCTI Science, IncCuraGen CorporationCurevedaCytori TherapeuticsCytoSorbents, Inc.DBV TechnologiesDeyDiaCartaDiaMedicaDOR BioPharmaDova PharmaceuticalsDow Chemical Co.Duke University Medical CenterDynavaxEd Laboratories, Inc.Edison PharmaEli Lilly and CompanyEminentEnterade, LLCEntrinsic Health SolutionsEpistemEpitek, Inc.Eukarion, IncExponential Biotherapies, IncFibrogenFirstString Research, Inc.Foresee PharmaceuticalsFujisawaFull Spectrum OmegaG1 TherapeuticsGenentechGenzymeGeorgetown UniversityGlaxo/SmithklineGreer LaboratoriesHA Cell TechnologyHemostemHollis EdenHuman GhrelinHumanetics CorporationIcahn School of Medicine at Mount SinaiIDEC PharmaceuticalsIlexImmune DesignImmuneRegenImmunex CorporationInflamaxInnate Immunotherapeutics LimitedInnovation PathwaysInverseonInvionInvivoSciences, IncJanssen Research &amp; Development, LLCJB TherapeuticsJohnson &amp; JohnsonKyowa Hakko Kirin Co., Ltd.KYOWA KIRIN PHARMACEUTICAL DEVELOPMENT, INCLawrence Berkeley National LaboratoryLignaMedLongevica Pharmaceuticals Inc.MacroGenics, IncMaxygen, IncMedestea BiotechMedical College of WisconsinMedical University of South CarolinaMedImmuneMeditor Pharmaceuticals, Ltd.Medtronic MiniMedMercia PhMetroHealth Medical CenterMillenium PharmaceuticalsMitosMotus Pharmaceuticals, Inc.Multi-Party AgreementMylanN8 Medical LLCN8 Medical, Inc.NanoPass TechnologiesNeoImmuneTech, Inc.NeostemNestle Health ScienceNeumedicinesNeurocrine BiosciencesNIDDKNippon KayakuNovartisNovaScreen Biosciences CorporationNovelosNOW FoodsNuvo Research AGOcera TherapeuticsOHSU Center for Regenerative Medicine in OregonOnconova Therapeutics, Inc.OnyxOre PharmaceuticalsOsiris Therapeutics, Inc.Ossium Health, Inc.Ovation PharmaceuticalsPaloma Pharmaceuticals, Inc.ParinGenixPennsylvania State UniversityPfizerPharmaceutical Product Development (PPD)Pharmacia Diagnostics ABPhylogix, Inc.PhysiocrinesPhysioGenix, Inc.Pinnacle Biologics, Inc.Pluristem Therapeutic Inc.Point TherapeuticsPowderJect Technologies LimitedProMetic BioSciences, Inc.Proteome SystemsRadiation Control Technologies, IncRadix TherapeuticsReata Pharmaceuticals, Inc.RegeneronRepligenRestorGenix, Inc.Rhythm Pharmaceuticals, IncRocheRx Bio, Inc.Sangstat Medical CorporationSanofi, Inc.Seattle GeneticsSEPPIC IncSloan Kettering Institute for Cancer ResearchSmithKline Beecham CorporationSoligenix, IncSologenix, IncSouthwest Research InstituteSRI  InternationalSt. Camillus MedicalSynedgenTajCo IncTargazymeTDeltaSTemple UniversityTerapioTevaThe Institutes for Pharmaceutical DiscoveryTikoMed ABTobira Therapeutics, Inc.Tricorder DiagnosticsTunitas Therapeutics, Inc.UCB Pharma S.A. BelgiumUCLAUniversity of Arkansas for Medical SciencesUniversity of California San DiegoUniversity of EmoryUniversity of FloridaUniversity of Kansas Medical CenterUniversity of North Carolina at Chapel HillUniversity of PennsylvaniaUniversity of Pittsburgh Medical CenterUniversity of RochesterUniversity of UtahUniversity of VirginiaUS Biotest, Inc.ViforViraCorVitaerisWake Forest School of MedicineWyeth PharmaceuticalsWyeth-Ayerst ResearchXomaYale Universityzz-test1zz-test2zz-test-firefox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddCompany2&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddCompany2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1_1_21_2']/td/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.19.38.0001'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreement Number'])[1]/following::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.19.82.0044'])[1]/following::select[1]</value>
   </webElementXpaths>
</WebElementEntity>
