<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddProduct2_3</name>
   <tag></tag>
   <elementGuidId>a8b911b2-7eb7-4431-86ba-c13dfc4e59fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddProduct2_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddProduct2_3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddProduct2_3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setProductInfo(this.id);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- None -3-D tissues (platform technologies)AB103Actemra (tocilizumab)Adipose-Derived Stem Cells &amp; Regenerative CellsAdvair DiskusAEOL 10150Aflunov (MF59-adjuvanted)Aflunov (MF59-unadjuvanted)Ajulemic AcidAlutard SQALXN-4100 (TPO)Amb a 1Amevive (alefacept)AMG 157 (anti-TSLP)AMG 714  (anti-IL-15 antibody)Amifostine (WR1064)Amino Acid Cocktailangiotensin peptidesAnti IL-17 mabAnti-ceramide antibodyAnti-Il12Anti-IL-5 (mepolizumab)anti-TGF-B antibodyanti-TNFAR101ARA 290Aralast NPARQ 501ARQ 900ASMase pathway in GI tractAssay Reagent KitsAST-120AtorvastatinAvonexBAC-3BaminerceptBB3BCN512Belatacept (LEA29Y)BelimumabBIO300BMS-188667BMS-224818BMS-224819Bone Marrow bankBPIBrentuximab (Adcentris)C22TTC2E5Ca-DTPACampath-1HCaptoprilCarfilzomibCat allergen extractsCat DanderCat-PADCat-PAD &amp; placebo for Cat-PADCBLB-502CBLB-612CD 34 Reagent KitsCD3+/CD19+ depleted bone marrowCDK4/6 InhibitorsCDX-301CenicrivirocCeragenins (Cationic Steroid Antibiotics)CeramideCG53135-05 (FGF-20)Chalcone derivative (2-trifluoromethyl-2'-methoxychalone)Characterized Peanut AllergenChemetCLT008Cockroach Allergen Extractcongener compoundsCTLA4-IgG4mDeltaGDeoxyspergualinDIM (3DM99DupilumabEA-230ECIS Based Automated Stem cell functionality AssayEDL2000EFK2 inhibitorEMP-123EnalaprilEnterade-REntericSorbEpi-1AEPI-743EpiPenEpiPen Jr.Epix-107Epix-111Epix-112ErythropoietinEtanerceptEUK-189Fab59FG-4539Fibroblast Growth Factor peptide (FGF-P)Flaxseed (Z6748)Flonase Nasal SprayFlovent DiskusFlt3 Receptor-Interacting Lectin (FRIL)GenisteinGlucopyranosyl Lipid A (GLA)Glycerinated Peanut Allergenic ExtractGranexin GelGrazaxGTS-21H1N1 (Influenza A) 2009 S-01v VaccineH5N1 Flu AdjuvantH5N1 Flu VaccineHemp OilhOKT3 (anti-CD3)HOPO derivativesHouse dust mite- mixHuman iPS cell manufacturing platformhuman recombinant thrombopoietinhyaluronic acidIDEC-131 (anti-CD154)IL-12Immune Globulin IntravenousImmunostimnlary oligodeoxyribonucleotide conjugate (AIC)Imprime WGPInfliximabIntradermal Fcy1-Fel d1 fusion protein (GFD)IPW5371IsletIsolex 300i Disposable SetsIsolex 300i Magneticcell Selection System MachineIsothiouronium derivativesJBT-101Keyhole Limpet Hemocyanin (KLH)Leucotropin (GM-CSF)LeukineLHRH-AntLovastatin TabletsLow Molecular Weight Dextran SulfateLulizumabMAS-1Maxy-G34MC8  insertsMEDI-507Mesenchymal Stem CellsMGA-031MicronJet600 needlesMIS416moleculesMontanide ISA 51 VGMontanide ISA 51 VG Sterilemouse Myeloid Progenitor Cells (mMPc)MozobilMultiPepMultiStemN/ANadololNBI-5788Neulasta (pegfilgrastim)Neumune (androst-5-ene-3bNeupogenNilotinibNon-Fat Dry Milk (NFD Milk)NOV-002NplateNRF2 upregulatorsNU206 (R-Spondin 1)Nucala (mepolizumab)ODSHOligonucleotide morpholino to CD47ON 01210.Na (Ex-Rad)Oral DTPAOrencia (abatacept)Otelixizumabotelixizumab and sirukumabP529PAAGPBI-1402Peanut Protein Oral Immunotherapy (AR101)PEGylation IgG fusionphosphonolPhysiocrinesplacebo for Abataceptplacebo for AMG 157placebo for Aralast NPplacebo for Atorvastatinplacebo for Cat-PADplacebo for Cockroach Allergen Extractplacebo for Flovent Diskusplacebo for Nadololplacebo for Rituxanplacebo for Viaskin Peanutplacebo for XolairPLacental eXpanded (PLX-RAD) cellsPleiotropin (PTN)Plerixafor (AMD3100)PoC BiodosimeterPPARgamma ligandsPre-Implantation Factor (PIF)PREMEAPrograf (tacrolimus)Proleukin (IL-2)RadilexRagweed Allergen Immunostimulatory Sequence ConjugateRapamune (sirolimus)rBPI-21Regulatory T cells (Treg)Relamorelin (RM-131)RG2077 (CTLA4-IG)Rituxan (rituximab)RLIP76RM-131RN168RWJ-800088Rx100Rx101Secoisolariciresinaol diglucosides (SDGs)Secukinumab (anti-IL-17)SGX202 (oral beclomethasone dipropionate or BDP)SGX942SphingosineStandardized Cat Hair ExtractstatinsSynexan (SP001)synthetic triterpenoids RTA 401synthetic triterpenoids RTA 402TabalostatTBO-filgrastimT-cell epitode peptidesTempolTeplizumabThymoglobulinTimothy grassTP508TPOmTrichuris suis ova (TSO)TXA127 (formulated angiotensin 1-7)Unadjuvanted H1N1 Influenza Virus VaccineVelaferminVelcade (bortezomib)Ventolin HFA (albuterol sulfate)Very Small Embryonic-Like cells (VSELs)Viaskin PeanutViral Panel (human samples)Vitamin D3WF10Xolair (omalizumab)XOMA 052Yel 002Yel/Rad 1/2Yel/Rad 1/2 derivativesZenapax (daclizumab)Zn-DTPAZortress (Everolimus)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddProduct2_3&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddProduct2_3']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1_1_21_2_24_3']/td/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.19.38.0001'])[1]/following::select[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreement Number'])[1]/following::select[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.19.27.0010'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[3]/td/select</value>
   </webElementXpaths>
</WebElementEntity>
